repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks: []
    # hooks:
    #   - id: mypy
    #     args: ["--explicit-package-bases"]
        # args: ["--strict", "--explicit-package-bases"]
